name: npm-publish
title: Publish on NPM
image: codefresh/npm-publish:latest
tag: "0.1"
version: "0.1"
description: Publishes a nodejs package to NPM registry
categories:
- Featured
- Deployment
sources:
- https://github.com/codefresh-contrib/npm-publish
maintainers:
- name: Jakob Stuart
  email: ""
icon: https://raw.githubusercontent.com/codefresh-plugins/npm-publish/master/icon.jpg
envs:
- name: NPM_TOKEN
  type: ""
  description: token of npm account (required)
