title: Publish on NPM
version: 0.1
image: codefresh/npm-publish:latest
description: Publishes a nodejs package to NPM registry
categories:
  - Featured
  - Deployment
sources:
  - 'https://github.com/codefresh-contrib/npm-publish'
icon: 'https://authy.com/wp-content/uploads/npm-logo.png'
maintainers:
  - name: Jakob Stuart
envs:
  - name: NPM_TOKEN 
    description: 'token of npm account (required)'
